name: financial_literacy_frontend
description: A Flutter frontend for the Financial Literacy App with Material Design 3 and AI chatbot
version: 1.0.1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.2.1
  shared_preferences: ^2.2.2
  material_design_icons_flutter: ^7.0.7296
  flutter_spinkit: ^5.2.0
  carousel_slider: ^4.2.1
  uuid: ^4.0.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  sqflite: ^2.3.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  sqflite_common_ffi: ^2.3.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bank_logo.png
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700